/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.dangkydangnhap;

import btl.FormBai.FormQuanLy;
import btl.dulieu.ketnoidltaikhoan;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author MSI
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTK = new javax.swing.JFormattedTextField();
        btnThoat = new javax.swing.JButton();
        txtMK = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        rdHienMK = new javax.swing.JRadioButton();
        btnDangKy = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ĐĂNG NHẬP HỆ THỐNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 6, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 210, -1));

        jLabel4.setBackground(new java.awt.Color(153, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên Đăng Nhập:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 86, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mật Khẩu:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 155, -1, -1));

        txtTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTKMouseEntered(evt);
            }
        });
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        txtTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTKKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTKKeyReleased(evt);
            }
        });
        jPanel1.add(txtTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 86, 202, -1));

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        txtMK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMKKeyReleased(evt);
            }
        });
        jPanel1.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 155, 202, -1));

        btnDangNhap.setBackground(new java.awt.Color(255, 0, 0));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        btnDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnDangNhapKeyReleased(evt);
            }
        });
        jPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        rdHienMK.setText("Hiện Mât Khẩu");
        rdHienMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdHienMKMouseClicked(evt);
            }
        });
        jPanel1.add(rdHienMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        btnDangKy.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangKyMouseClicked(evt);
            }
        });
        jPanel1.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/Images/HEHE.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    public int dem=0;
    public void dangnhap()
    {
         boolean check = false;
        try {
            // TODO add your handling code here:
            ketnoidltaikhoan kn= new ketnoidltaikhoan();
            ResultSet rs= kn.GetTK();
             
            while(rs.next())
            {
                if(rs.getString(1).equalsIgnoreCase(txtTK.getText())&&
                        rs.getString("matkhau").equalsIgnoreCase(txtMK.getText()))
                {
                    if(rs.getString(3).equalsIgnoreCase("1"))
                    {
                        this.dispose();
                        FormQuanLy a = new FormQuanLy(1,txtTK.getText(),txtMK.getText());
                       // a.quyenADMIN(1);
                        a.setVisible(true);
                    }
                    else
                    {
                        this.dispose();
                        FormQuanLy a = new FormQuanLy(8,txtTK.getText(),txtMK.getText());
                        //a.quyenADMIN(2);
                        a.setVisible(true);
                    }
                    check=true;
                    break;
                    
                }
            }
            if(check==false)
            {
                txtTK.setText("");
                 txtMK.setText("");
                dem++;
                JOptionPane.showMessageDialog(null, "Tài Khoản Mật Khẩu Không Đúng");
            }
            if(dem==3)
            {
                int rs1= JOptionPane.showConfirmDialog(null, "Sai Tài Khoản Hoặc Mật Khẩu Bạn Có Muốn Đăng Ký Tài Khoản Mới", "Thông Báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                //int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa dữ liệu thẻ này không", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(rs1==JOptionPane.YES_OPTION)
                {
                    DangKy a= new DangKy();
                    this.dispose();
                    a.setVisible(true);
                }
                else
                {
                    txtTK.setText("");
                    txtMK.setText("");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
       dangnhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

     private static String convertToLowerCase(String text) {
        // Chuyển đổi toàn bộ văn bản thành chữ thường
        return text.toLowerCase();
    }

    
    private void rdHienMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdHienMKMouseClicked
        // TODO add your handling code here:
      
        if(rdHienMK.isSelected())
        {
            
           // txtMK.setText(lowercaseText); 
           // txtMK.setText("        ");
            txtMK.setEchoChar((char) 0);
        }
        else
        {
            // Chuyển đổi toàn bộ văn bản thành mật khẩu
                txtMK.setEchoChar('*');
        }
    }//GEN-LAST:event_rdHienMKMouseClicked

    private void btnDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKyMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DangKy a= new DangKy();
        a.setVisible(true);
    }//GEN-LAST:event_btnDangKyMouseClicked

    private void txtTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKKeyPressed
        // TODO add your handling code here:
      //  if(evt.getKeyChar()==)
    }//GEN-LAST:event_txtTKKeyPressed

    private void txtTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTKMouseEntered
        // TODO add your handling code here:
       // txtMK.requestFocus();
    }//GEN-LAST:event_txtTKMouseEntered

    private void txtTKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtMK.requestFocus();
        }
    }//GEN-LAST:event_txtTKKeyReleased

    private void txtMKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            btnDangNhap.requestFocus();
        }
    }//GEN-LAST:event_txtMKKeyReleased

    private void btnDangNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDangNhapKeyReleased
        // TODO add your handling code here:if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             dangnhap();
        }
    }//GEN-LAST:event_btnDangNhapKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdHienMK;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JFormattedTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
