/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.FormBai;

import static btl.FormBai.FormNhanVien.quyen;
import btl.dulieu.ketnoicsdl;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class FomCaLam extends javax.swing.JFrame {

    /**
     * Creates new form FomCaLam
     */
    public static int quyen;
    public static String us,pw;
    public FomCaLam(int q,String tk,String mk) {
        initComponents();
        quyen=q;
        us=tk;
        pw=mk;
        shownut();
        ShowTable();
        Loai();
         setLocationRelativeTo(null);
    }

    public void Loai()
    {
        DefaultComboBoxModel model = (DefaultComboBoxModel)txtBD.getModel();
        
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcalam");
            int i=0;
            while(rs.next())
            {
                model.addElement(rs.getString("batdau"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
                DefaultComboBoxModel model2 = (DefaultComboBoxModel)txtKT.getModel();
        
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcalam");
            int i=0;
            while(rs.next())
            {
                model2.addElement(rs.getString("ketthuc"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void shownut()
    {
        if(quyen!=1)
        {
            btnThem.setVisible(false);
            btnSua.setVisible(false);
            btnXoa.setVisible(false);
        }
        else
        {
            
        }
    }
    public boolean checktg()
    {
        boolean check=true;
        int batdau=Integer.parseInt ((String) txtBD.getSelectedItem());
        int ketthuc=Integer.parseInt ((String) txtKT.getSelectedItem());
        if(batdau>=ketthuc)
        {
            check=false;
        }
        return check;
    }
    public int Dem()
    {int dem=0;
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcalam");
            while(rs.next())
            {
                dem++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void ShowTable()
    {
        DefaultTableModel model =(DefaultTableModel)tbCaLam.getModel();
        model.setRowCount(Dem());
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcalam");
            int i=0;
            while(rs.next())
            {
                tbCaLam.setValueAt(rs.getString("macalam"), i, 0);
                 tbCaLam.setValueAt(rs.getString("tencalam"), i, 1);
                  tbCaLam.setValueAt(rs.getString("batdau"), i, 2);
                   tbCaLam.setValueAt(rs.getString("ketthuc"), i, 3);
                    
                     i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBD = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtKT = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCaLam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Ca Làm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Ca Làm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã Ca Làm");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });
        jPanel2.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 234, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bắt Đầu");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 117, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tên Ca Làm");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 234, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Kết Thúc");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        txtBD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtBDItemStateChanged(evt);
            }
        });
        jPanel2.add(txtBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        txtKT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtKTItemStateChanged(evt);
            }
        });
        jPanel2.add(txtKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Ca Làm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbCaLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbCaLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Ca Làm", "Tên Ca Làm", "Bắt Đầu", "Kết Thúc"
            }
        ));
        tbCaLam.setRowHeight(35);
        tbCaLam.setShowVerticalLines(true);
        tbCaLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCaLamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCaLam);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, 260));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 840, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void txtBDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtBDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBDItemStateChanged

    public boolean kttrung()
    {
        boolean check=true;
        try {
            ketnoicsdl  kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcalam");
            while(rs.next())
            {
                if(rs.getString("macalam").equalsIgnoreCase(txtMa.getText()))
                {
                    check=false;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FomCaLam.class.getName()).log(Level.SEVERE, null, ex);
        }
        return check;
    }
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn= new ketnoicsdl();
        String maca=txtMa.getText();
        String tennv=txtTen.getText();
        int batdau=Integer.parseInt ((String) txtBD.getSelectedItem());
        int ketthuc=Integer.parseInt ((String) txtKT.getSelectedItem());
        if(kttrung())
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Thêm", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                 if(ktrong(maca)==false||ktrong(tennv)==false||ktrong((String) txtBD.getSelectedItem())==false
                        ||ktrong((String) txtBD.getSelectedItem())==false)
                {
                      
                      JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                     
                }
                else
                {
                     if(checktg()==true)
                      {
                          kn.ThemCaLam(maca, tennv, batdau, ketthuc);
                            JOptionPane.showMessageDialog(null, "Thêm Thành Công");
                      }
                     else
                     {
                          JOptionPane.showMessageDialog(null, "Bắt Đầu Phải Bé Hơn Kết Thúc");
                     }
                
                }
            }
             
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Ca Làm Này Đã Có");
        }
       
        ShowTable();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn= new ketnoicsdl();
        String maca=txtMa.getText();
        String tennv=txtTen.getText();
       int batdau=Integer.parseInt ((String) txtBD.getSelectedItem());
        int ketthuc=Integer.parseInt ((String) txtKT.getSelectedItem());
         if(kttrung())
        {
           JOptionPane.showMessageDialog(null, "Ca Làm Này Không Tồn Tại");         
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Sửa Thông Tin", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                 if(ktrong(maca)==false||ktrong(tennv)==false||ktrong((String) txtBD.getSelectedItem())==false
                        ||ktrong((String) txtBD.getSelectedItem())==false)
                {
                      
                      JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                 else
                 {
                      if(checktg()==true)
                      {
                           kn.SuaCaLam(maca, tennv, batdau, ketthuc);
                  JOptionPane.showMessageDialog(null, "Sửa Thành Công");
                      }
                     else
                     {
                          JOptionPane.showMessageDialog(null, "Bắt Đầu Phải Bé Hơn Kết Thúc");
                     }
                   
                 }
                   
            }
        }
      
        ShowTable();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn= new ketnoicsdl();
        String maca=txtMa.getText();
        String tennv=txtTen.getText();
        int batdau=Integer.parseInt ((String) txtBD.getSelectedItem());
        int ketthuc=Integer.parseInt ((String) txtKT.getSelectedItem());
          if(kttrung())
        {
           JOptionPane.showMessageDialog(null, "Ca Làm Này Không Tồn Tại");         
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Xoá Ca Làm Này", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                
                if(ktrong(maca)==false||ktrong(tennv)==false||ktrong((String) txtBD.getSelectedItem())==false
                        ||ktrong((String) txtBD.getSelectedItem())==false)
                {
                      
                      JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                 else
                 {
                 kn.XoaCaLam(maca);
                 JOptionPane.showMessageDialog(null, "Xoá Thành Công");
                 }
            }
        }
       
        ShowTable();
    }//GEN-LAST:event_btnXoaMouseClicked
    public boolean ktrong(String kt)
    {
        boolean check=true;
        if(kt.equalsIgnoreCase(""))
        {
            check=false;
        }
        return check;
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FormQuanLy a= new FormQuanLy(quyen,us,pw);
        a.setVisible(true);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void txtKTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtKTItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKTItemStateChanged

    private void tbCaLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCaLamMouseClicked
        // TODO add your handling code here:
        int vitri=tbCaLam.getSelectedRow();
        txtMa.setText((String) tbCaLam.getValueAt(vitri, 0));
        txtTen.setText((String) tbCaLam.getValueAt(vitri, 1));
        txtBD.setSelectedItem((String) tbCaLam.getValueAt(vitri, 2));
        txtKT.setSelectedItem((String) tbCaLam.getValueAt(vitri, 3));

    }//GEN-LAST:event_tbCaLamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FomCaLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FomCaLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FomCaLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FomCaLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FomCaLam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCaLam;
    private javax.swing.JComboBox<String> txtBD;
    private javax.swing.JComboBox<String> txtKT;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
