/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.FormBai;

import btl.dulieu.ketnoicsdl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class FormChucVu extends javax.swing.JFrame {

    /**
     * Creates new form FormChucVu
     */
    public int quyen ;
    public String us,pw;
    public FormChucVu(int q,String tk,String mk) {
        initComponents();
        ShowTable();
        nut();
        us=tk;
        pw=mk;
        quyen=q;
        Loai();
         setLocationRelativeTo(null);
    }

    public void nut()
    {
        if(quyen!=1)
        {
            btnSua.setVisible(false);
            btnThem.setVisible(false);
            btnXoa.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        txtGia = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChucVu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Tài Khoản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Chức Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã Chức Vụ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Giá Mỗi Giờ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 117, -1, -1));

        txtLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiActionPerformed(evt);
            }
        });
        jPanel2.add(txtLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 234, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tên Chức Vụ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 234, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        txtGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtGiaItemStateChanged(evt);
            }
        });
        jPanel2.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Chức Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Chức Vụ", "Tên Chức Vụ", "Giá Mỗi Giờ"
            }
        ));
        tbChucVu.setRowHeight(35);
        tbChucVu.setShowVerticalLines(true);
        tbChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChucVu);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, 260));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 840, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Loai()
    {Set<String> Tap = new HashSet<>();
        try {
            
            DefaultComboBoxModel model = (DefaultComboBoxModel)txtGia.getModel();
            ketnoicsdl kn=new ketnoicsdl();
            ResultSet rs=kn.GetData("tbchucvu");
            while(rs.next())
            {
                 String value = rs.getString("dongia");
                Tap.add(value);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FormChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
            for (String value : Tap) {
            txtGia.addItem(value);
        }
    }
    private void txtLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiActionPerformed

    
    public boolean ktrong(String kt)
    {
        boolean check=true;
        if(kt.equalsIgnoreCase(""))
        {
            check=false;
        }
        return check;
    }
  public int Dem()
    {int dem=0;
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbchucvu");
            while(rs.next())
            {
                dem++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void ShowTable()
    {
        DefaultTableModel model =(DefaultTableModel)tbChucVu.getModel();
        model.setRowCount(Dem());
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbchucvu");
            int i=0;
            while(rs.next())
            {
                tbChucVu.setValueAt(rs.getString("loainv"), i, 0);
                 tbChucVu.setValueAt(rs.getString("tenloai"), i, 1);
                  tbChucVu.setValueAt(rs.getString("dongia"), i, 2);
                   
                     i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public boolean kttrung()
    {
        boolean check=true;
        try {
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbchucvu");
            String ma=txtLoai.getText();
            while(rs.next())
            {
                if(ma.equalsIgnoreCase(rs.getString("loainv")))
                {
                    check=false;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        return check;
    }
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn =new ketnoicsdl();
        String loai=txtLoai.getText();
        String ten=txtTen.getText();
       
       double gia=Double.parseDouble((String) txtGia.getSelectedItem());
        
        if(kttrung())
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Thêm", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                if(ktrong(loai)==false||ktrong(ten)==false||ktrong((String) txtGia.getSelectedItem())==false)
                {

                    JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else
                {
                    kn.themchuvu(loai, ten, gia);
                    JOptionPane.showMessageDialog(null, "Thêm Thành Công");
                }
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Tài Khoản Này Đã Có");
        }

        ShowTable();
    }//GEN-LAST:event_btnThemMouseClicked

    
    private void txtGiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtGiaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaItemStateChanged

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn =new ketnoicsdl();
        String loai=txtLoai.getText();
        String ten=txtTen.getText();
       
        double gia=Double.parseDouble((String) txtGia.getSelectedItem());
        if(kttrung())
        {
            JOptionPane.showMessageDialog(null, "Chức Vụ Này Không Tồn Tại");
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Sửa Thông Tin", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                if(ktrong(loai)==false||ktrong(ten)==false||ktrong((String) txtGia.getSelectedItem())==false)
                {

                    JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else
                {
                    kn.suachuvu(loai, ten, gia);
                    JOptionPane.showMessageDialog(null, "Sửa Thành Công");
                }
            }
        }

        ShowTable();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:

        ketnoicsdl kn =new ketnoicsdl();
        String loai=txtLoai.getText();
        String ten=txtTen.getText();
       
        int gia=Integer.parseInt((String) txtGia.getSelectedItem());
        if(kttrung())
        {
            JOptionPane.showMessageDialog(null, "Chức Vụ Này Không Tồn Tại");
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Xoá Chức Vụ Này", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                if(ktrong(loai)==false)
                {

                    JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else
                {
                    kn.xoachucvu(ten);
                    JOptionPane.showMessageDialog(null, "Xoá Thành Công");
                }
            }
        }

        ShowTable();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FormQuanLy a= new FormQuanLy(1,us,pw);
        a.setVisible(true);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void tbChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChucVuMouseClicked
        // TODO add your handling code here:
        int vitri=tbChucVu.getSelectedRow();
        txtLoai.setText((String) tbChucVu.getValueAt(vitri, 0));
        txtTen.setText((String) tbChucVu.getValueAt(vitri, 1));
        txtGia.setSelectedItem((String) tbChucVu.getValueAt(vitri, 2));

    }//GEN-LAST:event_tbChucVuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FormChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbChucVu;
    private javax.swing.JComboBox<String> txtGia;
    private javax.swing.JTextField txtLoai;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
