/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.FormBai;

import static btl.FormBai.FormNhanVien.quyen;
import btl.dulieu.ketnoicsdl;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class FormCongViec extends javax.swing.JFrame {

    /**
     * Creates new form TimKiemCaLam
     */
    public static int quyen;
    public static String us,pw;
    public FormCongViec(int q,String tk,String mk) {
        initComponents();
        quyen=q;
        us=tk;
        pw=mk;
        shownut();
        ShowTable();
        Loai();
         setLocationRelativeTo(null);
    }

    public boolean ktrong(String kt)
    {
        boolean check=true;
        if(kt.equalsIgnoreCase(""))
        {
            check=false;
        }
        return check;
    }
     public void Loai()
    {
        
           DefaultComboBoxModel model1 = (DefaultComboBoxModel)txtMa.getModel();
        
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbnhanvien");
            int i=0;
            while(rs.next())
            {
                model1.addElement(rs.getString("manv"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                DefaultComboBoxModel model2 = (DefaultComboBoxModel)txtCa.getModel();
        
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcalam");
            int i=0;
            while(rs.next())
            {
                model2.addElement(rs.getString("macalam"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
     public void shownut()
    {
        if(quyen!=1)
        {
            btnThem.setVisible(false);
              btnSua.setVisible(false);
                btnXoa.setVisible(false);
        }
        else
        {
            
        }
    }

     public int Dem()
    {int dem=0;
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcongviec");
            while(rs.next())
            {
                dem++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void ShowTable()
    {
        DefaultTableModel model =(DefaultTableModel)tbCongViec.getModel();
        model.setRowCount(Dem());
        try {
            
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs=kn.GetData("tbcongviec");
            int i=0;
            while(rs.next())
            {
                tbCongViec.setValueAt(rs.getString("manv"), i, 0);
                 tbCongViec.setValueAt(rs.getString("macalam"), i, 1);        
                    tbCongViec.setValueAt(rs.getString("ngaylam"), i, 4);
                     tbCongViec.setValueAt(rs.getString("ghichu"), i, 5);                     
                     
                ResultSet rs2=kn.GetData("tbnhanvien");
                int i2=0;
                while(rs2.next())
                {
                       if(rs.getString("manv").equalsIgnoreCase(rs2.getString("manv")))
                       {
                           tbCongViec.setValueAt(rs2.getString("tennv"), i, 2);
                             tbCongViec.setValueAt(rs2.getString("loainv"), i, 3);
                       }
                      
                         
                }
                i++;
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        txtCa = new javax.swing.JComboBox<>();
        txtNgayLam = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCongViec = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Công Việc");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Công Việc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Ghi Chú");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Mã Ca Làm");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 117, -1, -1));

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtMaItemStateChanged(evt);
            }
        });
        jPanel2.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Ngày Làm");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        jPanel2.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mã Nhân Viên");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 350, 130));

        txtCa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtCaItemStateChanged(evt);
            }
        });
        jPanel2.add(txtCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        txtNgayLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtNgayLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 350));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Công Việc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbCongViec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Mã Ca Làm", "Tên Nhân Viên", "Loai Nhân Viên", "Ngày Làm", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCongViec.setRowHeight(35);
        tbCongViec.setShowVerticalLines(true);
        tbCongViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCongViecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCongViec);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, 260));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 840, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCongViecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCongViecMouseClicked
        // TODO add your handling code here:
        int vitri=tbCongViec.getSelectedRow();
        txtMa.setSelectedItem((String) tbCongViec.getValueAt(vitri, 0));
         txtCa.setSelectedItem((String) tbCongViec.getValueAt(vitri, 1));
         txtNgayLam.setText((String) tbCongViec.getValueAt(vitri, 4));
         txtGhiChu.setText((String) tbCongViec.getValueAt(vitri, 5));
        
    }//GEN-LAST:event_tbCongViecMouseClicked

    private void txtCaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtCaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaItemStateChanged

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FormQuanLy a= new FormQuanLy(quyen,us,pw);
        a.setVisible(true);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
        this.dispose();
        TimKiemCongViec a= new TimKiemCongViec(quyen,us,pw);
        a.setVisible(true);
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn= new ketnoicsdl();
        String manv=(String) txtMa.getSelectedItem();
        String maca=(String) txtCa.getSelectedItem();
        String ngaylam= txtNgayLam.getText();
        String ghichu=txtGhiChu.getText();
        if(kttrung())
        {
            JOptionPane.showMessageDialog(null, "Công Việc Này Vẫn Rỗng");
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Xoá Công Việc Này", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                if(ktrong(manv)==false)
                {

                    JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else

                {
                    kn.XoaCongViec(maca,manv);
                    JOptionPane.showMessageDialog(null, "Xoá Thành Công");
                }

            }
        }

        ShowTable();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn= new ketnoicsdl();
        String manv=(String) txtMa.getSelectedItem();
        String maca=(String) txtCa.getSelectedItem();
        String ngaylam= txtNgayLam.getText();
        String ghichu=txtGhiChu.getText();
        if(kttrung())
        {
            JOptionPane.showMessageDialog(null, "Công Việc Này Vẫn Rỗng");
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Sửa Thông Tin", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                if(ktrong(manv)==false||ktrong(maca)==false||ktrong(ngaylam)==false
                    ||ktrong(ghichu)==false)
                {

                    JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else

                {
                    kn.SuaCongViec(manv,maca, ngaylam, ghichu);
                    JOptionPane.showMessageDialog(null, "Sửa Thành Công");
                }

            }
        }

        ShowTable();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        ketnoicsdl kn= new ketnoicsdl();
        String manv=(String) txtMa.getSelectedItem();
        String maca=(String) txtCa.getSelectedItem();
        String ngaylam= txtNgayLam.getText();
        String ghichu=txtGhiChu.getText();
        if(kttrung())
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Thêm", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                if(ktrong(manv)==false||ktrong(maca)==false||ktrong(ngaylam)==false
                    ||ktrong(ghichu)==false)
                {

                    JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else

                {
                    kn.ThemCongViec(manv,maca, ngaylam, ghichu);
                    JOptionPane.showMessageDialog(null, "Thêm Thành Công");
                }

            }

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Công Việc Này Đã Có");
        }

        ShowTable();
    }//GEN-LAST:event_btnThemMouseClicked

    private void txtMaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtMaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaItemStateChanged

    public boolean kttrung()
    {
        boolean check=true;
        try {
            ketnoicsdl kn= new ketnoicsdl();
            ResultSet rs= kn.GetData("tbcongviec");
            String manv=(String) txtMa.getSelectedItem();
            String maca=(String) txtCa.getSelectedItem();
            String ngay=(String) txtNgayLam.getText();
            while(rs.next())
            {
                if(rs.getString("manv").equalsIgnoreCase(manv)&&rs.getString("macalam").equalsIgnoreCase(maca)&&rs.getString("ngaylam").equalsIgnoreCase(ngay))
                {
                    check = false;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormCongViec.class.getName()).log(Level.SEVERE, null, ex);
        }
        return check;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FormCongViec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCongViec;
    private javax.swing.JComboBox<String> txtCa;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JComboBox<String> txtMa;
    private javax.swing.JTextField txtNgayLam;
    // End of variables declaration//GEN-END:variables
}
