/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.FormBai;

import btl.dulieu.ketnoidltaikhoan;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MSI
 */
public class FormTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form FormTaiKhoan
     */
    public static int quyen;
    public static String us,pw;
    public FormTaiKhoan(int q,String tk,String mk){
        initComponents();
        shownut();
        quyen=q;
        us=tk;
        pw=mk;
        ShowTable();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        txtQuyen = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTaiKhoan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Tài Khoản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tài Khoản");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Quyền");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 117, -1, -1));

        txtTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        jPanel2.add(txtTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 234, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mật Khẩu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 234, -1));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        txtQuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        txtQuyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtQuyenItemStateChanged(evt);
            }
        });
        jPanel2.add(txtQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Tài Khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tài Khoản", "Mật Khẩu", "Quyền"
            }
        ));
        tbTaiKhoan.setRowHeight(35);
        tbTaiKhoan.setShowVerticalLines(true);
        tbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTaiKhoan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, 260));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 840, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void shownut()
    {
        if(quyen!=1)
        {
            btnThem.setVisible(false);
              btnSua.setVisible(false);
                btnXoa.setVisible(false);
        }
        else
        {
            
        }
    }
    public int Dem()
    {
           int dem=0;
        try {
         
            ketnoidltaikhoan kn=new ketnoidltaikhoan();
            ResultSet rs=kn.GetTK();
            while(rs.next())
            {
                dem++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void ShowTable()
    {
        DefaultTableModel model=(DefaultTableModel) tbTaiKhoan.getModel();
        model.setRowCount(Dem());
        try {
         
            ketnoidltaikhoan kn=new ketnoidltaikhoan();
            ResultSet rs=kn.GetTK();
            int i=0;
            while(rs.next())
            {
                String quyen="User";
                if(rs.getString("quyen").equalsIgnoreCase("1"))
                {
                    quyen="Admin";
                }
                tbTaiKhoan.setValueAt(rs.getString("taikhoan"), i, 0);
                tbTaiKhoan.setValueAt(rs.getString("matkhau"), i, 1);
                tbTaiKhoan.setValueAt(quyen, i, 2);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

     public int DemQuyen()
    {
           int dem=0;
        try {
         
                int a;
            String quyen = (String) txtQuyen.getSelectedItem();
            if(quyen.equalsIgnoreCase("ADMIN"))
            {
                a=1;
            }
            else
            {
                a=2;
            }
            ketnoidltaikhoan kn=new ketnoidltaikhoan();
            ResultSet rs=kn.TKtheoQuyen(a);
            while(rs.next())
            {
                dem++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void ShowTableQuyen()
    {
        DefaultTableModel model=(DefaultTableModel) tbTaiKhoan.getModel();
        model.setRowCount(DemQuyen());
        try {
         
               int a;
            String quyen = (String) txtQuyen.getSelectedItem();
            if(quyen.equalsIgnoreCase("ADMIN"))
            {
                a=1;
            }
            else
            {
                a=2;
            }
            ketnoidltaikhoan kn=new ketnoidltaikhoan();
            ResultSet rs=kn.TKtheoQuyen(a);
            int i=0;
            while(rs.next())
            {
                
                tbTaiKhoan.setValueAt(rs.getString("taikhoan"), i, 0);
                tbTaiKhoan.setValueAt(rs.getString("matkhau"), i, 1);
                tbTaiKhoan.setValueAt(quyen, i, 2);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean ktratrung()
    {
        boolean check=true;
        try {
            ketnoidltaikhoan kn = new ketnoidltaikhoan();
            ResultSet rs=kn.GetTK();
            String tk=txtTK.getText();
            while(rs.next())
            {
                if(tk.equalsIgnoreCase(rs.getString("taikhoan")))
                {
                    check= false;
                    break;

                }
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(FormTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
         return check;
    }
    private void txtQuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtQuyenItemStateChanged
        // TODO add your handling code here:
        ShowTableQuyen();
    }//GEN-LAST:event_txtQuyenItemStateChanged

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        ketnoidltaikhoan kn =new ketnoidltaikhoan();
        String tk=txtTK.getText();
        String mk=txtMK.getText();
        int quyen;
        String a=(String) txtQuyen.getSelectedItem();
        if(a.equalsIgnoreCase("ADMIN"))
        {
            quyen=1;
        }
        else
        {
            quyen=2;
        }
        if(ktratrung())
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Thêm", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                   if(ktrong(tk)==false||ktrong(mk)==false||ktrong(a)==false)
                {
                      
                      JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else
                {
                kn.ThemTKAD(tk, mk, quyen);
                JOptionPane.showMessageDialog(null, "Thêm Thành Công");
                }
            }
             
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Tài Khoản Này Đã Có");
        }
       
        ShowTable();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        ketnoidltaikhoan kn =new ketnoidltaikhoan();
        String tk=txtTK.getText();
        String mk=txtMK.getText();
        int quyen;
        String a=(String) txtQuyen.getSelectedItem();
        if(a.equalsIgnoreCase("ADMIN"))
        {
            quyen=1;
        }
        else
        {
            quyen=2;
        }
        if(ktratrung())
        {
           JOptionPane.showMessageDialog(null, "Tài Khoản Này Không Tồn Tại");         
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Sửa Thông Tin", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                   if(ktrong(tk)==false||ktrong(mk)==false||ktrong(a)==false)
                {
                      
                      JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else
                {
                  kn.SuaTKAD(tk, mk, quyen);
                  JOptionPane.showMessageDialog(null, "Sửa Thành Công");
                }
            }
        }
      
        ShowTable();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        
       ketnoidltaikhoan kn =new ketnoidltaikhoan();
        String tk=txtTK.getText();
        String mk=txtMK.getText();
        int quyen;
        String a=(String) txtQuyen.getSelectedItem();
        if(a.equalsIgnoreCase("ADMIN"))
        {
            quyen=1;
        }
        else
        {
            quyen=2;
        }
        if(ktratrung())
        {
           JOptionPane.showMessageDialog(null, "Tài Khoản Này Không Tồn Tại");         
        }
        else
        {
            int kq=JOptionPane.showConfirmDialog(null, "Bạn Đã Chắc Chắn Xoá Tài Khoản Này", "Thông Báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(kq==JOptionPane.YES_OPTION)
            {
                   if(ktrong(tk)==false)
                {
                      
                      JOptionPane.showMessageDialog(null, "Cần Nhập Đầy Đủ Thông Tin");
                }
                else
                {
                 kn.XoaTKAD(tk);
                 JOptionPane.showMessageDialog(null, "Xoá Thành Công");
                }
            }
        }
        
        ShowTable();
    }//GEN-LAST:event_btnXoaMouseClicked

    public boolean ktrong(String kt)
    {
        boolean check=true;
        if(kt.equalsIgnoreCase(""))
        {
            check=false;
        }
        return check;
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FormQuanLy a= new FormQuanLy(quyen,us,pw);
        a.setVisible(true);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void tbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTaiKhoanMouseClicked
        // TODO add your handling code here:
        int vitri=tbTaiKhoan.getSelectedRow();
        txtTK.setText((String) tbTaiKhoan.getValueAt(vitri, 0));
        txtMK.setText((String) tbTaiKhoan.getValueAt(vitri, 1));
        txtQuyen.setSelectedItem((String) tbTaiKhoan.getValueAt(vitri, 2));
       

    }//GEN-LAST:event_tbTaiKhoanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FormTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTaiKhoan;
    private javax.swing.JTextField txtMK;
    private javax.swing.JComboBox<String> txtQuyen;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
