/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.FormBai;

import btl.dulieu.ketnoidltaikhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class FormDoiMK extends javax.swing.JFrame {

    /**
     * Creates new form FormDoiMK
     */
    public static String us,pw;
     public static int quyen;
    public FormDoiMK(int q,String tk,String mk) {
        initComponents();
        us=tk;
        pw=mk;
        quyen=q;
        Show();
         setLocationRelativeTo(null);
    }
    public void Show()
    {
        txtTK.setText(us);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMKCu = new javax.swing.JFormattedTextField();
        btnThoat = new javax.swing.JButton();
        txtMK = new javax.swing.JPasswordField();
        btnOK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtXacNhan = new javax.swing.JPasswordField();
        rdHienMK = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTK = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Đổi Mật Khẩu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 210, -1));

        jLabel4.setBackground(new java.awt.Color(153, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mật Khẩu Cũ:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mật Khẩu:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        txtMKCu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMKCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKCuActionPerformed(evt);
            }
        });
        jPanel1.add(txtMKCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 202, -1));

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        txtMK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 202, -1));

        btnOK.setBackground(new java.awt.Color(255, 0, 0));
        btnOK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, -1));

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Xác Nhận :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        txtXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 202, -1));

        rdHienMK.setText("Hiện Mật Khẩu");
        rdHienMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdHienMKMouseClicked(evt);
            }
        });
        jPanel1.add(rdHienMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/Images/HEHE.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setBackground(new java.awt.Color(153, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tên Tài Khoản");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        txtTK.setEnabled(false);
        txtTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        jPanel1.add(txtTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 202, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 567, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMKCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKCuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        ketnoidltaikhoan kn= new ketnoidltaikhoan();
        String mkcu=txtMKCu.getText();
        String mk=txtMK.getText();
        String xacnhan=txtXacNhan.getText();
        if(mkcu.equalsIgnoreCase(pw))
        {
             if(xacnhan.equalsIgnoreCase(mk))
        {
            
                
                int rs=JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Xác Nhận Đổi Không",
                    "Thông Báo", WIDTH);
                if(rs==JOptionPane.YES_OPTION)
                {
                    kn.DoiMatKhau(us, mk);
                    JOptionPane.showMessageDialog(null, "Mật Khẩu Đã Được Đổi");
                }
            
        }
        else
        {
            // txtTK.setText("");
            txtMK.setText("");
            txtXacNhan.setText("");

            JOptionPane.showMessageDialog(null, "Mật Khẩu Xác Nhận Phải Trùng Nhau");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Mật Khẩu Cũ Không Đúng");
        }
       

    }//GEN-LAST:event_btnOKActionPerformed

    private void rdHienMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdHienMKMouseClicked
        // TODO add your handling code here:

        if(rdHienMK.isSelected())
        {

            // txtMK.setText(lowercaseText);
            // txtMK.setText("        ");
            txtMK.setEchoChar((char) 0);
            txtXacNhan.setEchoChar((char) 0);
        }
        else
        {
            // Chuyển đổi toàn bộ văn bản thành mật khẩu
            txtMK.setEchoChar('*');
            txtXacNhan.setEchoChar('*');

        }
    }//GEN-LAST:event_rdHienMKMouseClicked

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormDoiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdHienMK;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JFormattedTextField txtMKCu;
    private javax.swing.JFormattedTextField txtTK;
    private javax.swing.JPasswordField txtXacNhan;
    // End of variables declaration//GEN-END:variables
}
