/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl.FormBai;

import btl.dulieu.ketnoicsdl;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MSI
 */
public class FromLuong extends javax.swing.JFrame {

    /**
     * Creates new form FromLuong
     */
    public static int quyen ;
    public static String us,pw;
    public FromLuong(int q,String tk,String mk) {
        initComponents();
        
        us=tk;
        pw=mk;
        gio();
        luong();
        ShowTable();
        themluong();
        ShowTable();
        quyen =q;
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSapXep = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLuong = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tìm Kiếm Công Việc");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã Nhân Viên");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });
        jPanel2.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 234, -1));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Sắp Xếp Lương");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtSapXep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc Định", "Tăng Dần", "Giảm Dần" }));
        txtSapXep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtSapXepItemStateChanged(evt);
            }
        });
        txtSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSapXepActionPerformed(evt);
            }
        });
        jPanel2.add(txtSapXep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Lương", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên ", "Loại Nhân Viên", "Đơn Giá", "Số Giờ Làm", "Lương"
            }
        ));
        tbLuong.setRowHeight(35);
        tbLuong.setShowVerticalLines(true);
        tbLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLuong);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 820, 250));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 840, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void gio()
    {
        ketnoicsdl kn=new ketnoicsdl();
        kn.UpdateGioLam();
    }
     public void luong()
    {
        ketnoicsdl kn=new ketnoicsdl();
        kn.UpdateLuong();
    }
     public boolean checknv()
     {
        boolean check=true;
          try {
            ketnoicsdl kn = new ketnoicsdl();
            //ResultSet rs=kn.GetData("tbcongviec");
            ResultSet rs=kn.MaNVLam();
            while(rs.next())
            {
                for(int i=0;i<tbLuong.getRowCount();i++)
                {
                    String ma=(String) tbLuong.getValueAt(i, 0);
                    //if(rs.getString("manv").equals(ma))
                     if(rs.getString("manv").equals(ma))
                    {
                        check=false;
                        
                    }
                    else
                    {
                        check=true;
                        break;
                        
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
          return check;
     }
     public void themluong()
     {
          if(checknv()==true)
          {
              //JOptionPane.showMessageDialog(null, tbLuong.getRowCount());
            JOptionPane.showMessageDialog(null, "Đã Cập Nhật Bảng Lương");
        try {
            ketnoicsdl kn = new ketnoicsdl(); 
            ResultSet rs=kn.MaNVLam();
            String ma="";
            String loai="";
            int i=0;
            while(rs.next())
            {
                ma=rs.getString("manv");
                 ResultSet rs1=kn.GetData("tbnhanvien");
                while(rs1.next())
              {
                      if(rs1.getString("manv").equalsIgnoreCase(ma))
                      {
                          loai=rs1.getString("loainv");    
                      } 
                      
              }
                boolean checkkk =true;
                for( int i1=i;i1<tbLuong.getRowCount();i1++)
                          { System.out.println("hang"+i1);
                              if(ma.equalsIgnoreCase((String) tbLuong.getValueAt(i1, 0)))
                              {
                                 checkkk= false;
                                 break;
                              }
                              else
                              {
                                 checkkk= true;
                                  //break; 
                              }
                              
                          }
                if(checkkk==true)
                 kn.themluong(ma, loai, 1, 1.0);
                i++;
                System.out.println("MA"+i);
            }
           
              

        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
          else
          {
               JOptionPane.showMessageDialog(null, "Bảng Lương Không Có Cập Nhật Nào Mới");
          }
     }
    public int Dem()
    {
        int dem=0;
        try {
          
            ketnoicsdl kn=new ketnoicsdl();
            ResultSet rs=kn.GetData("tbluong");
            while(rs.next())
            {
                dem++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void ShowTable()
    {
        DefaultTableModel model=(DefaultTableModel) tbLuong.getModel();
        model.setRowCount(Dem());
         try {
              gio();
        luong();
            ketnoicsdl kn=new ketnoicsdl();
            ResultSet rs=kn.GetData("tbluong");
            int i=0;
            ResultSet rs1=kn.GetData("tbnhanvien");
            ResultSet rs2=kn.GetData("tbchucvu");
            int i1=0;
            int i2=0;
            while(rs.next())
            {
                tbLuong.setValueAt(rs.getString("manv"), i, 0);
                 tbLuong.setValueAt(rs.getString("loainv"), i, 2);
                  tbLuong.setValueAt(rs.getString("sogiolam"), i, 4);
                   tbLuong.setValueAt(rs.getString("luong"), i, 5);      
                   while(rs1.next())
                   {
                       if(rs.getString("manv").equalsIgnoreCase(rs1.getString("manv")))
                       {
                            tbLuong.setValueAt(rs1.getString("tennv"), i1, 1);
                             i1++;
                       }              
                   }
                   rs1=kn.GetData("tbnhanvien");
                   while(rs2.next())
                   {
                       if(rs.getString("loainv").equalsIgnoreCase(rs2.getString("loainv")))
                       {
                            tbLuong.setValueAt(rs2.getString("dongia"), i2, 3);
                            i2++;
                       }                       
                   }   
                   rs2=kn.GetData("tbchucvu");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    public int DemMa()
    {
       
        int dem=0;
        try {
            
            ketnoicsdl kn=new ketnoicsdl();
            String ma= txtMa.getText();
            ResultSet rs1=kn.TimKiemLuong(ma);
            //ResultSet rs=kn.GetData("tbluong");
           
                while(rs1.next())
                {
                       
                       dem++;
                   
                }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    
    }
    public void ShowTableMa()
    {
        DefaultTableModel model=(DefaultTableModel) tbLuong.getModel();
        model.setRowCount(DemMa());
         try {
              gio();
        luong();
            ketnoicsdl kn=new ketnoicsdl();
            String ma =txtMa.getText();

           
            ResultSet rs=kn.TimKiemLuong(ma);
            int i=0;
            ResultSet rs1=kn.GetData("tbnhanvien");
            ResultSet rs2=kn.GetData("tbchucvu");
            int i1=0;
            int i2=0;
            while(rs.next())
            {
                tbLuong.setValueAt(rs.getString("manv"), i, 0);
                 tbLuong.setValueAt(rs.getString("loainv"), i, 2);
                  tbLuong.setValueAt(rs.getString("sogiolam"), i, 4);
                   tbLuong.setValueAt(rs.getString("luong"), i, 5);      
                   while(rs1.next())
                   {
                       if(rs.getString("manv").equalsIgnoreCase(rs1.getString("manv")))
                       {
                            tbLuong.setValueAt(rs1.getString("tennv"), i1, 1);
                             i1++;
                       }              
                   }
                   rs1=kn.GetData("tbnhanvien");
                   while(rs2.next())
                   {
                       if(rs.getString("loainv").equalsIgnoreCase(rs2.getString("loainv")))
                       {
                            tbLuong.setValueAt(rs2.getString("dongia"), i2, 3);
                            i2++;
                       }                       
                   }   
                   rs2=kn.GetData("tbchucvu");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void TimKiem()
    {
       
            ShowTableMa();
        
    }
    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
          gio();
        luong();
       TimKiem();
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FormQuanLy a= new FormQuanLy(quyen,us,pw);
        a.setVisible(true);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void tbLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLuongMouseClicked
        // TODO add your handling code here:
        //        int vitri=tbCongViec.getSelectedRow();
        //        txtMa.setSelectedItem((String) tbCongViec.getValueAt(vitri, 0));
        //        txtCa.setSelectedItem((String) tbCongViec.getValueAt(vitri, 1));
        //        txtNgayLam.setText((String) tbCongViec.getValueAt(vitri, 4));
        //        txtGhiChu.setText((String) tbCongViec.getValueAt(vitri, 5));
    }//GEN-LAST:event_tbLuongMouseClicked

    public void ShowTableTang()
    {
        DefaultTableModel model=(DefaultTableModel) tbLuong.getModel();
        model.setRowCount(Dem());
         try {
              gio();
             luong();
            ketnoicsdl kn=new ketnoicsdl();
            ResultSet rs=kn.GetDataTang();
            int i=0;
            ResultSet rs1=kn.GetData("tbnhanvien");
            ResultSet rs2=kn.GetData("tbchucvu");
            int i1=0;
            int i2=0;
            while(rs.next())
            {
                tbLuong.setValueAt(rs.getString("manv"), i, 0);
                 tbLuong.setValueAt(rs.getString("loainv"), i, 2);
                  tbLuong.setValueAt(rs.getString("sogiolam"), i, 4);
                   tbLuong.setValueAt(rs.getString("luong"), i, 5);      
                   while(rs1.next())
                   {
                       if(rs.getString("manv").equalsIgnoreCase(rs1.getString("manv")))
                       {
                            tbLuong.setValueAt(rs1.getString("tennv"), i1, 1);
                             i1++;
                       }              
                   }
                   rs1=kn.GetData("tbnhanvien");
                   while(rs2.next())
                   {
                       if(rs.getString("loainv").equalsIgnoreCase(rs2.getString("loainv")))
                       {
                            tbLuong.setValueAt(rs2.getString("dongia"), i2, 3);
                            i2++;
                       }                       
                   }   
                   rs2=kn.GetData("tbchucvu");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void ShowTableGiam()
    {
        DefaultTableModel model=(DefaultTableModel) tbLuong.getModel();
        model.setRowCount(Dem());
         try {
              gio();
        luong();
            ketnoicsdl kn=new ketnoicsdl();
            ResultSet rs=kn.GetDataGiam();
            int i=0;
            ResultSet rs1=kn.GetData("tbnhanvien");
            ResultSet rs2=kn.GetData("tbchucvu");
            int i1=0;
            int i2=0;
            while(rs.next())
            {
                tbLuong.setValueAt(rs.getString("manv"), i, 0);
                 tbLuong.setValueAt(rs.getString("loainv"), i, 2);
                  tbLuong.setValueAt(rs.getString("sogiolam"), i, 4);
                   tbLuong.setValueAt(rs.getString("luong"), i, 5);      
                   while(rs1.next())
                   {
                       if(rs.getString("manv").equalsIgnoreCase(rs1.getString("manv")))
                       {
                            tbLuong.setValueAt(rs1.getString("tennv"), i1, 1);
                             i1++;
                       }              
                   }
                   rs1=kn.GetData("tbnhanvien");
                   while(rs2.next())
                   {
                       if(rs.getString("loainv").equalsIgnoreCase(rs2.getString("loainv")))
                       {
                            tbLuong.setValueAt(rs2.getString("dongia"), i2, 3);
                            i2++;
                       }                       
                   }   
                   rs2=kn.GetData("tbchucvu");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FromLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void SapXep()
    {
        String loaisx=(String) txtSapXep.getSelectedItem();
        
        if(loaisx.equalsIgnoreCase("Giảm Dần"))
        {  gio();
        luong();
            ShowTableGiam();
        }
        if(loaisx.equalsIgnoreCase("Tăng Dần"))
        {  gio();
            luong();
            ShowTableTang();
        }
        if(loaisx.equalsIgnoreCase("Mặc Định"))
        {   gio();
            luong();
            ShowTable();
        }
    }
    private void txtSapXepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtSapXepItemStateChanged
        // TODO add your handling code here:
        SapXep();
    }//GEN-LAST:event_txtSapXepItemStateChanged

    private void txtSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSapXepActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FromLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLuong;
    private javax.swing.JTextField txtMa;
    private javax.swing.JComboBox<String> txtSapXep;
    // End of variables declaration//GEN-END:variables
}
